"""
KPI catalogue — 50+ standard SAP B1 / ERP metrics seeded at tenant bootstrap.
Each KPI is domain-tagged and includes a formula string for documentation.
"""

from __future__ import annotations

from typing import TypedDict


class KPIDefinitionEntry(TypedDict, total=False):
    name: str
    display_name: str
    description: str
    formula: str
    unit: str
    aggregation_method: str   # sum | avg | count | min | max | ratio
    display_format: str       # currency | percent | number | integer
    domain: str


SYSTEM_KPIS: list[KPIDefinitionEntry] = [
    # ── FINANCE ───────────────────────────────────────────────────────────────
    {
        "name": "total_revenue",
        "display_name": "Total Revenue",
        "description": "Sum of all posted sales invoice amounts in system currency.",
        "formula": "SUM(OINV.DocTotalSy) WHERE Cancelled='N'",
        "unit": "currency",
        "aggregation_method": "sum",
        "display_format": "currency",
        "domain": "finance",
    },
    {
        "name": "gross_profit",
        "display_name": "Gross Profit",
        "description": "Revenue minus cost of goods sold.",
        "formula": "SUM(OINV.DocTotalSy) - SUM(INV1.GrossBuyPr * INV1.Quantity)",
        "unit": "currency",
        "aggregation_method": "sum",
        "display_format": "currency",
        "domain": "finance",
    },
    {
        "name": "gross_margin_pct",
        "display_name": "Gross Margin %",
        "description": "Gross profit as a percentage of revenue.",
        "formula": "(Gross Profit / Total Revenue) * 100",
        "unit": "percent",
        "aggregation_method": "ratio",
        "display_format": "percent",
        "domain": "finance",
    },
    {
        "name": "accounts_receivable_balance",
        "display_name": "Accounts Receivable Balance",
        "description": "Total open A/R balance across all customers.",
        "formula": "SUM(OCRD.Balance) WHERE CardType='C'",
        "unit": "currency",
        "aggregation_method": "sum",
        "display_format": "currency",
        "domain": "finance",
    },
    {
        "name": "accounts_payable_balance",
        "display_name": "Accounts Payable Balance",
        "description": "Total open A/P balance across all vendors.",
        "formula": "SUM(OCRD.Balance) WHERE CardType='S'",
        "unit": "currency",
        "aggregation_method": "sum",
        "display_format": "currency",
        "domain": "finance",
    },
    {
        "name": "overdue_receivables",
        "display_name": "Overdue Receivables",
        "description": "A/R invoices past due date.",
        "formula": "SUM(OINV.DocTotal - OINV.PaidToDate) WHERE DocStatus='O' AND DocDueDate < TODAY",
        "unit": "currency",
        "aggregation_method": "sum",
        "display_format": "currency",
        "domain": "finance",
    },
    {
        "name": "days_sales_outstanding",
        "display_name": "Days Sales Outstanding (DSO)",
        "description": "Average number of days to collect payment after a sale.",
        "formula": "(AR Balance / Total Revenue) * Days in Period",
        "unit": "days",
        "aggregation_method": "ratio",
        "display_format": "number",
        "domain": "finance",
    },
    {
        "name": "days_payable_outstanding",
        "display_name": "Days Payable Outstanding (DPO)",
        "description": "Average days to pay vendors.",
        "formula": "(AP Balance / COGS) * Days in Period",
        "unit": "days",
        "aggregation_method": "ratio",
        "display_format": "number",
        "domain": "finance",
    },
    {
        "name": "total_expenses",
        "display_name": "Total Expenses",
        "description": "Sum of all posted A/P invoice amounts.",
        "formula": "SUM(OPCH.DocTotalSy) WHERE Cancelled='N'",
        "unit": "currency",
        "aggregation_method": "sum",
        "display_format": "currency",
        "domain": "finance",
    },
    {
        "name": "net_cash_flow",
        "display_name": "Net Cash Flow",
        "description": "Incoming payments minus outgoing payments in the period.",
        "formula": "SUM(ORCT.DocTotal) - SUM(OVPM.DocTotal)",
        "unit": "currency",
        "aggregation_method": "sum",
        "display_format": "currency",
        "domain": "finance",
    },
    {
        "name": "tax_collected",
        "display_name": "Tax Collected (Output VAT)",
        "description": "Total VAT/tax on sales invoices.",
        "formula": "SUM(OINV.VatSum) WHERE Cancelled='N'",
        "unit": "currency",
        "aggregation_method": "sum",
        "display_format": "currency",
        "domain": "finance",
    },
    {
        "name": "tax_paid",
        "display_name": "Tax Paid (Input VAT)",
        "description": "Total VAT/tax on purchase invoices.",
        "formula": "SUM(OPCH.VatSum) WHERE Cancelled='N'",
        "unit": "currency",
        "aggregation_method": "sum",
        "display_format": "currency",
        "domain": "finance",
    },
    # ── SALES ─────────────────────────────────────────────────────────────────
    {
        "name": "total_sales_orders",
        "display_name": "Total Sales Orders",
        "description": "Count of open or closed sales orders.",
        "formula": "COUNT(ORDR.DocEntry) WHERE Cancelled='N'",
        "unit": "count",
        "aggregation_method": "count",
        "display_format": "integer",
        "domain": "sales",
    },
    {
        "name": "sales_order_value",
        "display_name": "Sales Order Value",
        "description": "Total value of open sales orders.",
        "formula": "SUM(ORDR.DocTotalSy) WHERE DocStatus='O' AND Cancelled='N'",
        "unit": "currency",
        "aggregation_method": "sum",
        "display_format": "currency",
        "domain": "sales",
    },
    {
        "name": "average_order_value",
        "display_name": "Average Order Value",
        "description": "Average sales order total.",
        "formula": "AVG(ORDR.DocTotalSy) WHERE Cancelled='N'",
        "unit": "currency",
        "aggregation_method": "avg",
        "display_format": "currency",
        "domain": "sales",
    },
    {
        "name": "quotation_conversion_rate",
        "display_name": "Quotation Conversion Rate",
        "description": "Percentage of quotations converted to sales orders.",
        "formula": "COUNT(Orders derived from quotes) / COUNT(OQUO) * 100",
        "unit": "percent",
        "aggregation_method": "ratio",
        "display_format": "percent",
        "domain": "sales",
    },
    {
        "name": "top_customers_revenue",
        "display_name": "Top Customer Revenue",
        "description": "Revenue attributed to top customers.",
        "formula": "SUM(OINV.DocTotalSy) GROUP BY CardCode ORDER BY SUM DESC",
        "unit": "currency",
        "aggregation_method": "sum",
        "display_format": "currency",
        "domain": "sales",
    },
    {
        "name": "sales_by_salesperson",
        "display_name": "Sales by Salesperson",
        "description": "Revenue breakdown per sales representative.",
        "formula": "SUM(OINV.DocTotalSy) GROUP BY SlpCode",
        "unit": "currency",
        "aggregation_method": "sum",
        "display_format": "currency",
        "domain": "sales",
    },
    {
        "name": "sales_returns_value",
        "display_name": "Sales Returns Value",
        "description": "Total value of sales credit memos.",
        "formula": "SUM(ORIN.DocTotalSy) WHERE Cancelled='N'",
        "unit": "currency",
        "aggregation_method": "sum",
        "display_format": "currency",
        "domain": "sales",
    },
    {
        "name": "return_rate",
        "display_name": "Return Rate",
        "description": "Sales returns as a percentage of revenue.",
        "formula": "Sales Returns Value / Total Revenue * 100",
        "unit": "percent",
        "aggregation_method": "ratio",
        "display_format": "percent",
        "domain": "sales",
    },
    {
        "name": "open_deliveries",
        "display_name": "Open Deliveries",
        "description": "Count of delivery notes not yet invoiced.",
        "formula": "COUNT(ODLN.DocEntry) WHERE DocStatus='O' AND Cancelled='N'",
        "unit": "count",
        "aggregation_method": "count",
        "display_format": "integer",
        "domain": "sales",
    },
    # ── PURCHASING ────────────────────────────────────────────────────────────
    {
        "name": "total_purchase_orders",
        "display_name": "Total Purchase Orders",
        "description": "Count of purchase orders.",
        "formula": "COUNT(OPOR.DocEntry) WHERE Cancelled='N'",
        "unit": "count",
        "aggregation_method": "count",
        "display_format": "integer",
        "domain": "purchasing",
    },
    {
        "name": "purchase_order_value",
        "display_name": "Purchase Order Value",
        "description": "Total value of open purchase orders.",
        "formula": "SUM(OPOR.DocTotalSy) WHERE DocStatus='O' AND Cancelled='N'",
        "unit": "currency",
        "aggregation_method": "sum",
        "display_format": "currency",
        "domain": "purchasing",
    },
    {
        "name": "total_purchases",
        "display_name": "Total Purchases",
        "description": "Total AP invoice amounts in the period.",
        "formula": "SUM(OPCH.DocTotalSy) WHERE Cancelled='N'",
        "unit": "currency",
        "aggregation_method": "sum",
        "display_format": "currency",
        "domain": "purchasing",
    },
    {
        "name": "purchase_by_vendor",
        "display_name": "Purchases by Vendor",
        "description": "Spend breakdown per vendor.",
        "formula": "SUM(OPCH.DocTotalSy) GROUP BY CardCode",
        "unit": "currency",
        "aggregation_method": "sum",
        "display_format": "currency",
        "domain": "purchasing",
    },
    {
        "name": "overdue_payables",
        "display_name": "Overdue Payables",
        "description": "AP invoices past due date.",
        "formula": "SUM(OPCH.DocTotal - OPCH.PaidToDate) WHERE DocStatus='O' AND DocDueDate < TODAY",
        "unit": "currency",
        "aggregation_method": "sum",
        "display_format": "currency",
        "domain": "purchasing",
    },
    {
        "name": "purchase_returns_value",
        "display_name": "Purchase Returns Value",
        "description": "Total value of AP credit memos.",
        "formula": "SUM(ORPC.DocTotalSy) WHERE Cancelled='N'",
        "unit": "currency",
        "aggregation_method": "sum",
        "display_format": "currency",
        "domain": "purchasing",
    },
    # ── INVENTORY ─────────────────────────────────────────────────────────────
    {
        "name": "total_stock_value",
        "display_name": "Total Stock Value",
        "description": "Current inventory value at average cost.",
        "formula": "SUM(OITW.OnHand * OITM.AvgPrice)",
        "unit": "currency",
        "aggregation_method": "sum",
        "display_format": "currency",
        "domain": "inventory",
    },
    {
        "name": "stock_on_hand",
        "display_name": "Stock On Hand",
        "description": "Total quantity in stock across all warehouses.",
        "formula": "SUM(OITW.OnHand)",
        "unit": "quantity",
        "aggregation_method": "sum",
        "display_format": "number",
        "domain": "inventory",
    },
    {
        "name": "items_below_min_stock",
        "display_name": "Items Below Minimum Stock",
        "description": "Count of items with on-hand quantity below reorder point.",
        "formula": "COUNT(OITM) WHERE OnHand < MinLevel",
        "unit": "count",
        "aggregation_method": "count",
        "display_format": "integer",
        "domain": "inventory",
    },
    {
        "name": "inventory_turnover",
        "display_name": "Inventory Turnover",
        "description": "Times inventory is sold and replaced in a period.",
        "formula": "COGS / Average Inventory Value",
        "unit": "ratio",
        "aggregation_method": "ratio",
        "display_format": "number",
        "domain": "inventory",
    },
    {
        "name": "days_inventory_outstanding",
        "display_name": "Days Inventory Outstanding (DIO)",
        "description": "Average days to sell inventory.",
        "formula": "(Average Inventory Value / COGS) * Days in Period",
        "unit": "days",
        "aggregation_method": "ratio",
        "display_format": "number",
        "domain": "inventory",
    },
    {
        "name": "slow_moving_items",
        "display_name": "Slow Moving Items",
        "description": "Items with no sales activity in the last 90 days.",
        "formula": "COUNT(OITM) WHERE last_sale_date < TODAY - 90 AND OnHand > 0",
        "unit": "count",
        "aggregation_method": "count",
        "display_format": "integer",
        "domain": "inventory",
    },
    {
        "name": "committed_stock",
        "display_name": "Committed Stock",
        "description": "Quantity reserved for open sales orders.",
        "formula": "SUM(OITW.IsCommited)",
        "unit": "quantity",
        "aggregation_method": "sum",
        "display_format": "number",
        "domain": "inventory",
    },
    {
        "name": "stock_on_order",
        "display_name": "Stock On Order",
        "description": "Quantity on open purchase orders.",
        "formula": "SUM(OITW.OnOrder)",
        "unit": "quantity",
        "aggregation_method": "sum",
        "display_format": "number",
        "domain": "inventory",
    },
    {
        "name": "available_to_promise",
        "display_name": "Available to Promise",
        "description": "On-hand minus committed plus on-order.",
        "formula": "OnHand - Committed + OnOrder",
        "unit": "quantity",
        "aggregation_method": "sum",
        "display_format": "number",
        "domain": "inventory",
    },
    {
        "name": "goods_receipts_count",
        "display_name": "Goods Receipts Count",
        "description": "Number of goods receipts posted in the period.",
        "formula": "COUNT(OGRPO.DocEntry) + COUNT(OIGE.DocEntry) WHERE Cancelled='N'",
        "unit": "count",
        "aggregation_method": "count",
        "display_format": "integer",
        "domain": "inventory",
    },
    # ── OPERATIONS ────────────────────────────────────────────────────────────
    {
        "name": "open_production_orders",
        "display_name": "Open Production Orders",
        "description": "Count of released / in-progress work orders.",
        "formula": "COUNT(OWOR.DocEntry) WHERE Status IN ('P','R') AND Cancelled='N'",
        "unit": "count",
        "aggregation_method": "count",
        "display_format": "integer",
        "domain": "operations",
    },
    {
        "name": "production_completion_rate",
        "display_name": "Production Completion Rate",
        "description": "Completed quantity vs planned quantity on work orders.",
        "formula": "SUM(OWOR.CmpltQty) / SUM(OWOR.PlannedQty) * 100",
        "unit": "percent",
        "aggregation_method": "ratio",
        "display_format": "percent",
        "domain": "operations",
    },
    {
        "name": "rejection_rate",
        "display_name": "Rejection Rate (Manufacturing)",
        "description": "Rejected quantity as percentage of planned production.",
        "formula": "SUM(OWOR.RjctQty) / SUM(OWOR.PlannedQty) * 100",
        "unit": "percent",
        "aggregation_method": "ratio",
        "display_format": "percent",
        "domain": "operations",
    },
    {
        "name": "active_employees",
        "display_name": "Active Employees",
        "description": "Current headcount of active employees.",
        "formula": "COUNT(OHEM.empID) WHERE Active='Y'",
        "unit": "count",
        "aggregation_method": "count",
        "display_format": "integer",
        "domain": "operations",
    },
    {
        "name": "on_time_delivery_rate",
        "display_name": "On-Time Delivery Rate",
        "description": "Deliveries made on or before promised date.",
        "formula": "COUNT(ODLN WHERE DocDate <= DueDate) / COUNT(ODLN) * 100",
        "unit": "percent",
        "aggregation_method": "ratio",
        "display_format": "percent",
        "domain": "operations",
    },
    # ── CROSS-DOMAIN ──────────────────────────────────────────────────────────
    {
        "name": "new_customers",
        "display_name": "New Customers",
        "description": "Count of new customer records created in the period.",
        "formula": "COUNT(OCRD) WHERE CardType='C' AND CreateDate >= period_start",
        "unit": "count",
        "aggregation_method": "count",
        "display_format": "integer",
        "domain": "sales",
    },
    {
        "name": "customer_count",
        "display_name": "Total Active Customers",
        "description": "Number of active, non-frozen customer records.",
        "formula": "COUNT(OCRD) WHERE CardType='C' AND validFor='Y' AND Froze='N'",
        "unit": "count",
        "aggregation_method": "count",
        "display_format": "integer",
        "domain": "sales",
    },
    {
        "name": "vendor_count",
        "display_name": "Total Active Vendors",
        "description": "Number of active, non-frozen supplier records.",
        "formula": "COUNT(OCRD) WHERE CardType='S' AND validFor='Y' AND Froze='N'",
        "unit": "count",
        "aggregation_method": "count",
        "display_format": "integer",
        "domain": "purchasing",
    },
    {
        "name": "revenue_per_employee",
        "display_name": "Revenue per Employee",
        "description": "Total revenue divided by active headcount.",
        "formula": "Total Revenue / Active Employees",
        "unit": "currency",
        "aggregation_method": "ratio",
        "display_format": "currency",
        "domain": "finance",
    },
    {
        "name": "cash_conversion_cycle",
        "display_name": "Cash Conversion Cycle",
        "description": "DIO + DSO - DPO.",
        "formula": "DIO + DSO - DPO",
        "unit": "days",
        "aggregation_method": "ratio",
        "display_format": "number",
        "domain": "finance",
    },
    {
        "name": "working_capital",
        "display_name": "Working Capital",
        "description": "Current assets minus current liabilities.",
        "formula": "AR Balance + Stock Value - AP Balance",
        "unit": "currency",
        "aggregation_method": "sum",
        "display_format": "currency",
        "domain": "finance",
    },
    {
        "name": "revenue_growth_rate",
        "display_name": "Revenue Growth Rate",
        "description": "Percentage change in revenue vs prior period.",
        "formula": "(Current Period Revenue - Prior Period Revenue) / Prior Period Revenue * 100",
        "unit": "percent",
        "aggregation_method": "ratio",
        "display_format": "percent",
        "domain": "finance",
    },
    {
        "name": "top_selling_items",
        "display_name": "Top Selling Items",
        "description": "Items by quantity sold in the period.",
        "formula": "SUM(INV1.Quantity) GROUP BY ItemCode ORDER BY SUM DESC",
        "unit": "quantity",
        "aggregation_method": "sum",
        "display_format": "number",
        "domain": "sales",
    },
    {
        "name": "credit_utilization",
        "display_name": "Credit Utilisation",
        "description": "Customer balance as a percentage of their credit limit.",
        "formula": "OCRD.Balance / OCRD.CreditLine * 100",
        "unit": "percent",
        "aggregation_method": "ratio",
        "display_format": "percent",
        "domain": "finance",
    },
]


async def seed_kpis(db, tenant_id) -> int:
    """
    Seed system KPIs for a tenant if not already present.
    Returns count of inserted records.
    """
    from sqlalchemy import select
    from app.models.semantic import KpiDefinition

    result = await db.execute(
        select(KpiDefinition.name).where(
            KpiDefinition.tenant_id == tenant_id,
            KpiDefinition.is_system.is_(True),
        )
    )
    existing = {r[0] for r in result.fetchall()}

    inserted = 0
    for kpi in SYSTEM_KPIS:
        if kpi["name"] in existing:
            continue
        db.add(KpiDefinition(
            tenant_id=tenant_id,
            name=kpi["name"],
            display_name=kpi["display_name"],
            description=kpi.get("description"),
            formula=kpi.get("formula"),
            unit=kpi.get("unit"),
            aggregation_method=kpi.get("aggregation_method", "sum"),
            display_format=kpi.get("display_format"),
            domain=kpi.get("domain", "finance"),
            is_active=True,
            is_system=True,
        ))
        inserted += 1

    await db.flush()
    return inserted
