"""Resize embedding columns from vector(1536) to vector(1024).

The platform now embeds with a local sentence-transformers model
(BAAI/bge-large-en-v1.5, 1024 dim) instead of a hosted 1536-dim API.
Embedding tables hold derived data that is regenerated by the embedder
pipelines, so existing rows (if any) are truncated rather than converted.

Revision ID: 0004
Revises: 0003
"""

from alembic import op

revision = "0004"
down_revision = "0003"
branch_labels = None
depends_on = None


def _resize(table: str, index: str, dim: int) -> None:
    op.execute(f"DROP INDEX IF EXISTS {index}")
    op.execute(f"TRUNCATE {table}")
    op.execute(f"ALTER TABLE {table} DROP COLUMN embedding")
    op.execute(
        f"ALTER TABLE {table} ADD COLUMN embedding vector({dim}) NOT NULL "
        f"DEFAULT array_fill(0, ARRAY[{dim}])::vector"
    )
    op.execute(f"ALTER TABLE {table} ALTER COLUMN embedding DROP DEFAULT")
    op.execute(f"""
        CREATE INDEX IF NOT EXISTS {index}
        ON {table} USING hnsw (embedding vector_cosine_ops)
        WITH (m = 16, ef_construction = 128)
    """)


def upgrade() -> None:
    _resize("tool_embeddings", "ix_tool_embeddings_hnsw", 1024)
    _resize("document_embeddings", "ix_doc_embeddings_hnsw", 1024)


def downgrade() -> None:
    _resize("tool_embeddings", "ix_tool_embeddings_hnsw", 1536)
    _resize("document_embeddings", "ix_doc_embeddings_hnsw", 1536)
